pipeline{
    agent any
    environment {
        PATH = "${M2_HOME}/bin:${PATH}"

    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/ravdy/javaloginapp.git'
            }
         }        
       stage('Build'){
            steps{
                bat 'mvn clean'
            }
         }
        stage('SonarQube analysis') {
 //   def scannerHome = tool 'SonarQube Scanner 4.7';
        steps{
        withSonarQubeEnv('sonarqube', envOnly: true) { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        bat "mvn sonar:sonarqube"
    }
        }
        }
       
    }
}
