pipeline{
    agent any
    environment {
        PATH = "${M2_HOME}/bin:${PATH}"

    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/ravdy/javaloginapp.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarQube Scanner 4.0.0.1744';
        steps{
        withSonarQubeEnv('sonarqube-8.9.7') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
